const FETCH_CATEGORIES_REQUEST = 'CATEGORIES/FETCH_REQUEST';
const FETCH_CATEGORIES_SUCCESS = 'CATEGORIES/FETCH_SUCCESS';
const FETCH_CATEGORIES_FAILURE = 'CATEGORIES/FETCH_FAILURE';

const FETCH_CATEGORY_REQUEST = 'CATEGORY/FETCH_REQUEST';
const FETCH_CATEGORY_SUCCESS = 'CATEGORY/FETCH_SUCCESS';
const FETCH_CATEGORY_FAILURE = 'CATEGORY/FETCH_FAILURE';

const CREATE_CATEGORY = 'CATEGORIES/CREATE';
const DELETE_CATEGORY = 'CATEGORIES/DELETE';

const CREATE_TODO_IN_CATEGORY_SUCCESS = 'CATEGORIES/CREATE_TODO_SUCCESS';
const DELETE_TODO_FROM_CATEGORY_SUCCESS = 'CATEGORIES/DELETE_TODO_SUCCESS';

export {
  FETCH_CATEGORIES_REQUEST,
  FETCH_CATEGORIES_SUCCESS,
  FETCH_CATEGORIES_FAILURE,
  FETCH_CATEGORY_FAILURE,
  FETCH_CATEGORY_REQUEST,
  FETCH_CATEGORY_SUCCESS,
  CREATE_CATEGORY,
  DELETE_CATEGORY,
  CREATE_TODO_IN_CATEGORY_SUCCESS,
  DELETE_TODO_FROM_CATEGORY_SUCCESS,
};
