const FETCH_TODOS_REQUEST = 'TODOS/FETCH_REQUEST';
const FETCH_TODOS_SUCCESS = 'TODOS/FETCH_SUCCESS';
const FETCH_TODOS_FAILURE = 'TODOS/FETCH_FAILURE';
const CREATE_TODO = 'TODOS/CREATE';
const DELETE_TODO = 'TODOS/DELETE';

export {
  FETCH_TODOS_REQUEST,
  FETCH_TODOS_SUCCESS,
  FETCH_TODOS_FAILURE,
  CREATE_TODO,
  DELETE_TODO,
};
