const FETCH_TWEETS_REQUEST = 'TWEETS/FETCH_REQUEST';
const FETCH_TWEETS_SUCCESS = 'TWEETS/FETCH_SUCCESS';
const FETCH_TWEETS_FAILURE = 'TWEETS/FETCH_FAILURE';

const NEW_TWEETS_SUBSCRIPTION = 'TWEETS/NEW_TWEETS_SUBSCRIPTION';
const PUSH_TWEETS_SUCCESS = 'TWEETS/PUSH_SUCCESS';

const ALL_TWEETS_READ = 'TWEETS/ALL_TWEETS_READ';

export {
  FETCH_TWEETS_REQUEST,
  FETCH_TWEETS_SUCCESS,
  FETCH_TWEETS_FAILURE,
  NEW_TWEETS_SUBSCRIPTION,
  PUSH_TWEETS_SUCCESS,
  ALL_TWEETS_READ,
};
